name: Deploy Published API Documantation

on:
  push:
    branches:
      - main
      # TODO: remove
      - feature/publish-api

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Start FastAPI server
        run: |
          uvicorn backend.app.main:app --reload --host 0.0.0.0 --port 8000 &
          sleep 10

      - name: Download OpenAPI JSON
        run: |
          wget http://127.0.0.1:8000/openapi.json -O openapi.json

      - name: Install redoc-cli
        run: |
          npm install -g redoc-cli

      - name: Generate REDOC static HTML
        run: |
          mkdir -p redoc
          npx redoc-cli bundle openapi.json -o redoc/index.html

      - name: Kill FastAPI server
        run: |
          pkill uvicorn

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./redoc
